---
- hosts: 127.0.0.1
  connection: local

  tasks:

  - name: Install PHP 5.6
    homebrew: name={{ item }} state=present
    with_items:
    - homebrew/php/php56
    when: php_active == "y" and php_version == "5"

  - name: Install PHP 7
    homebrew: name={{ item }} state=present
    with_items:
    - homebrew/php/php70
    when: php_active == "y" and php_version == "7"

  - name: Install Composer
    homebrew: name={{ item }} state=present
    with_items:
    - homebrew/php/composer
    when: php_active == "y" and php_composer == "y"

  - name: Install software
    homebrew_cask: name={{ item }} state=present
    with_items:
    - iterm2
    - sequel-pro
    - vagrant
    - vmware-fusion

  - name: Create personal file for oh-my-zsh shell
    file: path=~/.oh-my-zsh/custom/my.zsh state=touch

  - name: Create first alias
    lineinfile: dest=~/.oh-my-zsh/custom/my.zsh regexp="^alias ohmy=" line="alias ohmy='st ~/.oh-my-zsh/custom/my.zsh'"